/*
 * FormClienti.java
 *
 * Created on July 2, 2004, 3:46 PM
 */

package Formulare.ClientiUI;

import Sursa.Clienti;
import Sursa.Localitati;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.*;
import java.text.*;
import javax.swing.text.*;
import java.awt.event.*;
import utilitati.Utilitati;
import Formulare.interfata.*;
/**
 *
 * @author alex
 */
public class FormClienti extends javax.swing.JFrame{
    Connection conn;
    //private ArrayList sursaDateClienti;
    //private List sursaDateLocalitati;
    //private String[] localitati = {"6600", "5467", "6400","1900","5300"};
    /** Creates new form FormClienti */
    public FormClienti() {//throws Exception{
      initComponents();
      formateazaFields();
      adaugaListeneri();
      this.setTitle("Clienti");
      this.setSize(500, 380);
     this.setLocation(280,280);
      //*****************************************
      try{
      conn=Utilitati.getConexiune();
      ArrayList clienti=Clienti.getObjects(conn,"order by numepren");
      ArrayList localitati=Localitati.getObjects(conn, null);
      this.cboClienti.setModel(new DefaultComboBoxModel(clienti.toArray()));
      this.cboCodpost.setModel(new DefaultComboBoxModel(localitati.toArray()));
      this.refreshControale((Clienti)cboClienti.getSelectedItem());
      }
      catch(Exception e){Utilitati.tratareErori(e);}
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cboClienti = new javax.swing.JComboBox();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtCodcl = new javax.swing.JFormattedTextField();
        txtNumepren = new javax.swing.JFormattedTextField();
        cboCodpost = new javax.swing.JComboBox();
        txtAdresa = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSterg = new javax.swing.JButton();
        txtTelefon = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Date Clienti");
        setBackground(new java.awt.Color(51, 51, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        cboClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClientiActionPerformed(evt);
            }
        });
        cboClienti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboClientiItemStateChanged(evt);
            }
        });

        getContentPane().add(cboClienti, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 250, -1));

        btnPrevious.setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 20));

        btnNext.setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        txtCodcl.setBackground(new java.awt.Color(153, 204, 255));
        txtCodcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodclActionPerformed(evt);
            }
        });

        getContentPane().add(txtCodcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, -1));

        txtNumepren.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(txtNumepren, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));

        cboCodpost.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(cboCodpost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, -1));

        txtAdresa.setBackground(new java.awt.Color(153, 204, 255));
        txtAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresaActionPerformed(evt);
            }
        });

        getContentPane().add(txtAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, 80));

        jLabel1.setText("Cod Client");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 20));

        jLabel2.setText("Numepren");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 20));

        jLabel3.setText("Localitate");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 20));

        jLabel4.setText("Adresa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 20));

        jLabel5.setText("Telefon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 20));

        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, 20));

        btnSave.setBackground(new java.awt.Color(102, 204, 255));
        btnSave.setText("OK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 90, -1));

        btnCancel.setBackground(new java.awt.Color(102, 204, 255));
        btnCancel.setText("Abandon");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 90, -1));

        btnAdd.setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        btnAdd.setText("Adauga\n");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        btnSterg.setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        btnSterg.setText("Sterge");
        btnSterg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergActionPerformed(evt);
            }
        });

        getContentPane().add(btnSterg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 110, -1));

        txtTelefon.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 170, -1));

        txtEmail.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 170, -1));

        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        getContentPane().add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btnFirst.setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        btnFirst.setText("<<");
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 60, 20));

        btnLast.setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        btnLast.setText(">>");
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 60, 20));

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setText("Home ");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Alege Clientul");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 40));

        pack();
    }//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        new FrmPrincipal().show();
       this.hide();
    }//GEN-LAST:event_jToggleButton1ActionPerformed
public void refreshControale(Clienti objClienti){
    this.txtCodcl.setValue(objClienti.getCodcl());
    this.txtNumepren.setValue(objClienti.getNumepren());
    this.txtAdresa.setValue(objClienti.getAdresa());
    this.txtEmail.setValue(objClienti.getEmail());
    this.txtTelefon.setValue(objClienti.getTelefon());
      for (int i=0;i<this.cboCodpost.getItemCount();i++)
            if (((Localitati)this.cboCodpost.getItemAt(i)).getCodpost().equals(objClienti.getCodpost()))
            {this.cboCodpost.setSelectedIndex(i);break ;}
    
}
public void adaugaListeneri(){
  //CBOCODCLIENT
    this.cboClienti.addItemListener(new ItemListener(){
        public void itemStateChanged(ItemEvent evt){
         if (evt.getStateChange()==ItemEvent.DESELECTED)
             {
             if (((Clienti)evt.getItem()).getStare()!=Clienti.SINCRONIZAT)
                if (JOptionPane.showConfirmDialog(FormClienti.this, "Salvati modificarile efectuate ?",
                   "Client Modificat", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
                try{((Clienti)evt.getItem()).salveaza(FormClienti.this.conn);}
                       
                
                catch(Exception e){Utilitati.tratareErori(e);}
             else 
                    anuleazaModificari((Clienti)evt.getItem());
             }
          else
               refreshControale((Clienti)evt.getItem());
                   
        }
  });
//CBOCODPOST
   this.cboCodpost.addActionListener(new ActionListener(){
   public void actionPerformed(ActionEvent evt){
       Clienti objClienti=(Clienti)FormClienti.this.cboClienti.getSelectedItem();
       Localitati objLoc=(Localitati)cboCodpost.getSelectedItem();
       objClienti.setCodpost(objLoc.getCodpost());
               
       }
   });
   //BUTONUL SALVEAZA
   this.btnSave.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
      Clienti  objClienti=(Clienti)FormClienti.this.cboClienti.getSelectedItem();
   try{objClienti.salveaza(FormClienti.this.conn);}
      catch(Exception e){Utilitati.tratareErori(e);}
     //  FormClienti.this.updateFormular(objClienti);
    //   FormClienti.this.salveazaFormular(objClienti);
    }
   });
   
    
   //butonul abandon
   this.btnCancel.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
        anuleazaModificari((Clienti)FormClienti.this.cboClienti.getSelectedItem());
    }
   });
   //butonul Adauga
   this.btnAdd.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
       Clienti objClienti=new Clienti();
   objClienti.setCodpost(((Localitati)cboCodpost.getSelectedItem()).getCodpost());    
        FormClienti.this.cboClienti.addItem(objClienti);
        FormClienti.this.cboClienti.setSelectedItem(objClienti);
        FormClienti.this.txtCodcl.requestFocus();
    }
   });
   //butonul sterge
   this.btnSterg.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
      if (JOptionPane.showConfirmDialog(FormClienti.this,"Clientul curent va fi sters.Continuam?",
        "Client Modificat",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
        {
        Clienti objClienti = (Clienti)FormClienti.this.cboClienti.getSelectedItem();
        objClienti.setStare(Clienti.STERS);
      try {objClienti.salveaza(FormClienti.this.conn);
        FormClienti.this.cboClienti.removeItem(objClienti);
        }
        catch(Exception e){Utilitati.tratareErori(e);}
    }
    }
   });
  //butoane navigare
   this.btnNext.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
   /*  try{
         cboClienti.setSelectedIndex(cboClienti.getSelectedIndex()+1);
     }
     catch(IllegalArgumentException e){}    */
     if (cboClienti.getSelectedIndex() < cboClienti.getItemCount()-1)
            cboClienti.setSelectedIndex(cboClienti.getSelectedIndex()+1);
    }
   });
   this.btnFirst.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
   FormClienti.this.cboClienti.setSelectedIndex(0);         
    }
   });
   this.btnLast.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
  cboClienti.setSelectedIndex(cboClienti.getItemCount()-1);
    }
   });
   this.btnPrevious.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
    /* try{
         cboClienti.setSelectedIndex(cboClienti.getSelectedIndex()-1);
     }
     catch(IllegalArgumentException e){}    */
        if (cboClienti.getSelectedIndex()>0)
            cboClienti.setSelectedIndex(cboClienti.getSelectedIndex()-1);
    }
   });
  //input verifiers pentru textfieldurile de editare
   InputVerifierDate ivf=new InputVerifierDate();
   this.txtCodcl.setInputVerifier(ivf);
   this.txtNumepren.setInputVerifier(ivf);
   this.txtAdresa.setInputVerifier(ivf);
   this.txtTelefon.setInputVerifier(ivf);
   this.txtEmail.setInputVerifier(ivf);
}
/*
 private void updateFormular(Clienti objClienti){
        objClienti.setCodcl(new java.math.BigDecimal(txtCodcl.getValue().toString()));
        objClienti.setNumepren(txtNumepren.getValue().toString());
        objClienti.setAdresa(txtAdresa.getValue().toString());
        objClienti.setTelefon(new java.math.BigDecimal(txtTelefon.getValue().toString()));
        objClienti.setEmail(txtEmail.getValue().toString());
        objClienti.setCodpost((String)this.cboCodpost.getSelectedItem());
   }
  private void salveazaFormular(Clienti objClienti){
        try{
            int stare=objClienti.getStare();
            objClienti.salveaza(this.conn);
            if (stare==Clienti.STERS){   
                this.cboClienti.removeItemAt(this.cboClienti.getSelectedIndex());
                this.refreshFormular(((Clienti)this.cboClienti.getSelectedItem()));
            }
        }
        catch(Exception e){
            //tools.Utilitati.tratareErori(e);
        }
    }
 private void refreshFormular(Clienti objClienti){
        this.txtCodcl.setValue(objClienti.getCodcl());
        this.txtNumepren.setValue(objClienti.getNumepren());
        this.txtAdresa.setValue(objClienti.getAdresa());
        this.txtEmail.setValue(objClienti.getEmail());
        this.txtTelefon.setValue(objClienti.getTelefon());
        this.cboCodpost.setSelectedItem(objClienti.getCodpost());
    }*/
public void anuleazaModificari(Clienti objClient){
     if (objClient.getStare()==Clienti.NOU){  
           FormClienti.this.cboClienti.removeItem(objClient);
    }
    else
           try{objClient.refresh(FormClienti.this.conn);
               ItemListener[] lsnr=cboClienti.getItemListeners();
               lsnr[0].itemStateChanged(new ItemEvent(cboClienti,0,objClient,ItemEvent.SELECTED));
           }
           catch(Exception e){
               Utilitati.tratareErori(e);
           }
}
private void formateazaFields(){
    DecimalFormat formatInt=new java.text.DecimalFormat();
       formatInt.setMaximumFractionDigits(0);
       formatInt.setMaximumIntegerDigits(38);
       formatInt.setGroupingUsed(false);
       this.txtCodcl.setFormatterFactory(new DefaultFormatterFactory(
        new NumberFormatter(formatInt)));
       this.txtTelefon.setFormatterFactory(new DefaultFormatterFactory(
        new NumberFormatter(formatInt)));
       
}
public static void main(String args[])throws Exception{
   try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception ex){
            System.out.println("Se afiseaza formul Clientilor!!!!");
        }
    new FormClienti().show();
}
class InputVerifierDate extends InputVerifier{
    public boolean verify(JComponent input){
    if(input instanceof JFormattedTextField){
        JFormattedTextField ftf=(JFormattedTextField)input;
        JFormattedTextField.AbstractFormatter formatter=ftf.getFormatter();
        if(formatter!=null){
            String text=ftf.getText();
            if(text!=null&&!text.equals(""))
                try{
                    Object valNoua=formatter.stringToValue(text);
                    comiteModificari(ftf,valNoua);
                    return true;
                    
                }
                catch(ParseException e){
                    System.out.println("Invalid input");
                    return false;
                }
        }
    }
    return true;
    }
    public void comiteModificari(JFormattedTextField ftf,Object valNoua){
        Clienti objClienti=(Clienti)FormClienti.this.cboClienti.getSelectedItem();
        if(ftf==FormClienti.this.txtCodcl)
            objClienti.setCodcl(new java.math.BigDecimal(((Number)valNoua).doubleValue()));
        else if (ftf==FormClienti.this.txtNumepren)
            objClienti.setNumepren((String)valNoua);
        else if (ftf==FormClienti.this.txtAdresa)
            objClienti.setAdresa((String)valNoua);
        else if (ftf==FormClienti.this.txtEmail)
            objClienti.setEmail((String)valNoua);
        else if (ftf==FormClienti.this.txtTelefon)
            objClienti.setTelefon(new java.math.BigDecimal(((Number)valNoua).doubleValue()));
    }
    public boolean shouldYieldFocus(JComponent input){
        boolean inputValid=this.verify(input);
        if(!inputValid)
        {java.awt.Toolkit.getDefaultToolkit().beep();return false;}
        return true;
        
    }
    
}
    private void txtAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresaActionPerformed

    private void btnStergActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergActionPerformed
     
    
    }//GEN-LAST:event_btnStergActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      
    }//GEN-LAST:event_btnAddActionPerformed

    private void cboClientiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboClientiItemStateChanged
        // TODO add your handling code here:
   
    }//GEN-LAST:event_cboClientiItemStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCodclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodclActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:      
   
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void cboClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClientiActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cboClientiActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        // try {conn.close();} catch(Exception e){e.printStackTrace();}
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSterg;
    private javax.swing.JComboBox cboClienti;
    private javax.swing.JComboBox cboCodpost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JFormattedTextField txtAdresa;
    private javax.swing.JFormattedTextField txtCodcl;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtNumepren;
    private javax.swing.JFormattedTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}