/*
 * FrmReparatii.java
 *
 * Created on June 29, 2004, 1:22 AM
 */

package Formulare.grid.GridComplex;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.text.*;
import javax.swing.JTextField.*;
import Sursa.*;
import java.sql.*;
import java.util.*;
import javax.swing.table.*;
import java.math.BigDecimal;
import utilitati.*;
import Formulare.interfata.*;
/**
 *
 * @author alex
 */
public class FrmReparatii extends javax.swing.JFrame {
    
   Connection conn;
    /** Creates new form FrmArtRepar */
    public FrmReparatii() {
        initComponents();
        
        try{
           
        this.conn = Utilitati.getConexiune();
         formatGUIElements();
          ArrayList lstrepar = Reparatii.getObjects(conn,"order by codrepar");
          ArrayList lstclie = Clienti.getObjects(conn, "order by numepren");
          for (int i = 0 ; i<lstclie.size();i++)
              this.cboclient.addItem(lstclie.get(i));
             
          for (int i = 0 ; i<lstrepar.size();i++)
              this.cbocodrepar.addItem(lstrepar.get(i));    
      }
      catch (Exception e){Utilitati.tratareErori(e);}   
      
        
          
        
     /*   ModelJTableArtRepar modelDate=new ModelJTableArtRepar();
        this.tblArtRepar.setModel(modelDate);
        this.conn=modelDate.conexiune;
     
        ListSelectionModel modelSelectieGrid=this.tblArtRepar.getSelectionModel();
        modelSelectieGrid.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
    //pt combo din grid    
        TableColumn tc=tblArtRepar.getColumnModel().getColumn(1);
        try{
            java.util.ArrayList chitare=Chitare.getObjects(conn,"order by codchitara");
            tc.setCellRenderer(new ComboRendererChitare(chitare.toArray()));
            
        }
        catch(Exception e){
            Utilitati.tratareErori(e);
            
        }*/
     ///*****************   
        this.setLocation(280,280);
   
       
         
      
      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        Pbuton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbocodrepar = new javax.swing.JComboBox();
        primul = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        urmator = new javax.swing.JButton();
        PanelCenter = new javax.swing.JPanel();
        ultim = new javax.swing.JButton();
        Pgrid = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addrepar = new javax.swing.JButton();
        stergrepar = new javax.swing.JButton();
        okrepar = new javax.swing.JButton();
        cancelrepar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArtRepar = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        addartrepar = new javax.swing.JButton();
        stergartrepar = new javax.swing.JButton();
        salveazaartrepar = new javax.swing.JButton();
        cancelartrepar = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodrepar = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdatarepar = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cboclient = new javax.swing.JComboBox();
        txtvaltotalar = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Formular Facturi Sc MX SRL");
        setBackground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        setFont(new java.awt.Font("Times New Roman", 0, 14));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        Pbuton.setBackground(new java.awt.Color(239, 239, 247));
        Pbuton.setBorder(new javax.swing.border.TitledBorder(""));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel6.setText("Cod Reparatie\n");
        Pbuton.add(jLabel6);

        cbocodrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocodreparActionPerformed(evt);
            }
        });
        cbocodrepar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbocodreparItemStateChanged(evt);
            }
        });

        Pbuton.add(cbocodrepar);

        primul.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        primul.setForeground(new java.awt.Color(255, 255, 255));
        primul.setIcon(new javax.swing.ImageIcon("D:\\work\\feaa\\proiect_java\\files\\top.bmp"));
        primul.setText("|<<");
        primul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primulActionPerformed(evt);
            }
        });

        Pbuton.add(primul);

        anterior.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        anterior.setForeground(new java.awt.Color(255, 255, 255));
        anterior.setText("<<");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        Pbuton.add(anterior);

        urmator.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        urmator.setForeground(new java.awt.Color(255, 255, 255));
        urmator.setText(">>");
        urmator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urmatorActionPerformed(evt);
            }
        });

        Pbuton.add(urmator);

        PanelCenter.setLayout(new java.awt.BorderLayout());

        Pbuton.add(PanelCenter);

        ultim.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        ultim.setForeground(new java.awt.Color(255, 255, 255));
        ultim.setText(">>|");
        ultim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimActionPerformed(evt);
            }
        });

        Pbuton.add(ultim);

        getContentPane().add(Pbuton, java.awt.BorderLayout.NORTH);

        Pgrid.setLayout(new java.awt.BorderLayout());

        Pgrid.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBackground(new java.awt.Color(236, 239, 242));
        jPanel2.setBorder(new javax.swing.border.TitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));
        addrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        addrepar.setForeground(new java.awt.Color(255, 255, 255));
        addrepar.setText("Adauga");
        addrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addreparActionPerformed(evt);
            }
        });

        jPanel2.add(addrepar);

        stergrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        stergrepar.setForeground(new java.awt.Color(255, 255, 255));
        stergrepar.setText("Sterge");
        stergrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stergreparActionPerformed(evt);
            }
        });

        jPanel2.add(stergrepar);

        okrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        okrepar.setForeground(new java.awt.Color(255, 255, 255));
        okrepar.setText("Salveaza");
        okrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okreparActionPerformed(evt);
            }
        });

        jPanel2.add(okrepar);

        cancelrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        cancelrepar.setForeground(new java.awt.Color(255, 255, 255));
        cancelrepar.setText("Abandon");
        cancelrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelreparActionPerformed(evt);
            }
        });

        jPanel2.add(cancelrepar);

        Pgrid.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(202, 219, 255));
        jPanel3.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 200));
        jScrollPane1.setOpaque(false);
        tblArtRepar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        tblArtRepar.setForeground(new java.awt.Color(204, 204, 204));
        tblArtRepar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblArtRepar.setPreferredSize(new java.awt.Dimension(600, 600));
        jScrollPane1.setViewportView(tblArtRepar);

        jPanel3.add(jScrollPane1);

        Pgrid.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(241, 241, 247));
        jPanel4.setBorder(new javax.swing.border.TitledBorder(""));
        jPanel4.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        addartrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        addartrepar.setForeground(new java.awt.Color(255, 255, 255));
        addartrepar.setText("Adauga  ");
        addartrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addartreparActionPerformed(evt);
            }
        });

        jPanel4.add(addartrepar);

        stergartrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        stergartrepar.setForeground(new java.awt.Color(255, 255, 255));
        stergartrepar.setText("Sterge \n");
        stergartrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stergartreparActionPerformed(evt);
            }
        });

        jPanel4.add(stergartrepar);

        salveazaartrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        salveazaartrepar.setForeground(new java.awt.Color(255, 255, 255));
        salveazaartrepar.setText("Salveaza ");
        salveazaartrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salveazaartreparActionPerformed(evt);
            }
        });

        jPanel4.add(salveazaartrepar);

        cancelartrepar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        cancelartrepar.setForeground(new java.awt.Color(255, 255, 255));
        cancelartrepar.setText("Abandon");
        cancelartrepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelartreparActionPerformed(evt);
            }
        });

        jPanel4.add(cancelartrepar);

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setText("Home ");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jPanel4.add(jToggleButton1);

        Pgrid.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(Pgrid, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(javax.swing.UIManager.getDefaults().getColor("RadioButtonMenuItem.selectionBackground"));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cod Reparatie\n");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        txtcodrepar.setBackground(new java.awt.Color(204, 204, 204));
        txtcodrepar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodrepar.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jPanel1.add(txtcodrepar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 80, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Reparatie\n");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 40));

        txtdatarepar.setBackground(new java.awt.Color(204, 204, 204));
        txtdatarepar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatarepar.setFont(new java.awt.Font("Times New Roman", 1, 18));
        txtdatarepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatareparActionPerformed(evt);
            }
        });

        jPanel1.add(txtdatarepar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 120, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Client");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 40));

        cboclient.setBackground(new java.awt.Color(204, 204, 204));
        cboclient.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jPanel1.add(cboclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 250, 30));

        txtvaltotalar.setBackground(new java.awt.Color(204, 204, 204));
        txtvaltotalar.setEditable(false);
        txtvaltotalar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvaltotalar.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jPanel1.add(txtvaltotalar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 220, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Valoare Totala");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 150, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
         new FrmPrincipal().show();
       this.hide();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ultimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimActionPerformed
     FrmReparatii.this.cbocodrepar.setSelectedIndex(cbocodrepar.getItemCount()-1);
    }//GEN-LAST:event_ultimActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
            try{
      cbocodrepar.setSelectedIndex(cbocodrepar.getSelectedIndex()-1);
      }
      catch(IllegalArgumentException e)
      {
          
      }
    }//GEN-LAST:event_anteriorActionPerformed

    private void stergartreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stergartreparActionPerformed
    int idx= tblArtRepar.getSelectedRow();
    if (idx==-1)
        JOptionPane.showMessageDialog(this,"Selectati mai intai o linie!");
    else{
        ModelJTableArtRepar model= (ModelJTableArtRepar)tblArtRepar.getModel();
        model.stergLinie(idx);
        model.comiteModificari();
        tblArtRepar.revalidate();
        tblArtRepar.repaint();
    }
    }//GEN-LAST:event_stergartreparActionPerformed

    private void salveazaartreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salveazaartreparActionPerformed
    ModelJTableArtRepar model = (ModelJTableArtRepar)tblArtRepar.getModel();
   model.comiteModificari();
   tblArtRepar.revalidate();
   tblArtRepar.repaint();    
       
    }//GEN-LAST:event_salveazaartreparActionPerformed

    private void cancelartreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelartreparActionPerformed
     ModelJTableArtRepar model = (ModelJTableArtRepar)tblArtRepar.getModel();
     model.anulezModificari();
     tblArtRepar.revalidate();
     tblArtRepar.repaint();  
    }//GEN-LAST:event_cancelartreparActionPerformed

    private void addartreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addartreparActionPerformed
     ((ModelJTableArtRepar)tblArtRepar.getModel()).addLinieNoua(((Reparatii)cbocodrepar.getSelectedItem()).getCodrepar());
     tblArtRepar.revalidate();
     tblArtRepar.repaint();      
    }//GEN-LAST:event_addartreparActionPerformed

    private void cbocodreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocodreparActionPerformed
      this.refreshArtRepar();
    }//GEN-LAST:event_cbocodreparActionPerformed

    private void okreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okreparActionPerformed
   Reparatii repar=(Reparatii) this.cbocodrepar.getSelectedItem();
     this.updateBean(repar);
     this.salveaza(repar);
    }//GEN-LAST:event_okreparActionPerformed

    private void addreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addreparActionPerformed
       this.cbocodrepar.addItem(new Reparatii());
       this.txtcodrepar.setFocusable(true);
     this.cbocodrepar.setSelectedIndex(this.cbocodrepar.getItemCount()-1);
    }//GEN-LAST:event_addreparActionPerformed

    private void stergreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stergreparActionPerformed
    ((Reparatii)this.cbocodrepar.getSelectedItem()).setStare(Reparatii.STERS);
    }//GEN-LAST:event_stergreparActionPerformed

    private void cancelreparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelreparActionPerformed
        this.abandon((Reparatii)this.cbocodrepar.getSelectedItem());        // TODO add your handling code here:
    }//GEN-LAST:event_cancelreparActionPerformed

    private void primulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primulActionPerformed
     FrmReparatii.this.cbocodrepar.setSelectedIndex(0);
    }//GEN-LAST:event_primulActionPerformed

    private void cbocodreparItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbocodreparItemStateChanged
        
        if (evt.getStateChange()==ItemEvent.SELECTED)
          this.refreshForm((Reparatii) evt.getItem());     
    }//GEN-LAST:event_cbocodreparItemStateChanged

    private void txtdatareparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatareparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatareparActionPerformed

    private void urmatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urmatorActionPerformed
    try{
      cbocodrepar.setSelectedIndex(cbocodrepar.getSelectedIndex()+1);
      }
      catch(IllegalArgumentException e)
      {
          
      }
    }//GEN-LAST:event_urmatorActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    private void formatGUIElements(){
       // date calendaristice:
  /*     java.text.SimpleDateFormat formatData=new java.text.SimpleDateFormat("dd/MM/yyyy");
       formatData.setLenient(false);
       this.txtdatarepar.setFormatterFactory(new DefaultFormatterFactory(new DateFormatter(formatData)));
       // campuri numerice:
       java.text.DecimalFormat formatInt=new java.text.DecimalFormat("#");
       formatInt.setMinimumFractionDigits(0);
       formatInt.setMaximumIntegerDigits(15);
       this.txtcodrepar.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(formatInt)));
       
       java.text.DecimalFormat formatNumeric=new java.text.DecimalFormat("#");
       formatNumeric.setMinimumFractionDigits(0);
       formatNumeric.setMaximumIntegerDigits(16);
    
       this.txtvaltotalar.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(formatNumeric)));
      ((NumberFormatter)this.txtvaltotalar.getFormatter()).setAllowsInvalid(false);*/
    
     this.tblArtRepar.setModel(new ModelJTableArtRepar());
       TableColumn tc = this.tblArtRepar.getColumnModel().getColumn(1);
      /*  java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("dd/MM/yyyy");
      format.setLenient(false);
       tc.setCellRenderer(new FormattedRenderer(format));
       tc.setCellEditor(new FormattedEditor(format));
       
       java.text.DecimalFormat f=new java.text.DecimalFormat();
       f.setMaximumIntegerDigits(10);
       f.setMinimumFractionDigits(0);
       this.tblArtRepar.setDefaultRenderer(BigDecimal.class, new FormattedRenderer(f));
       this.tblArtRepar.setDefaultEditor(BigDecimal.class, new FormattedEditor(f));*/
       try{
       java.util.ArrayList chitare = Chitare.getObjects(conn,"order by codchitara");
       tc.setCellRenderer(new ComboRendererChitare(chitare.toArray()));
       tc.setCellEditor(new ComboEditorChitare(new JComboBox(chitare.toArray())));
       }
       catch (Exception e){
       Utilitati.tratareErori(e);
       }
       
    }
        public void refreshArtRepar(){
        Reparatii repar = (Reparatii)cbocodrepar.getSelectedItem();
        ((ModelJTableArtRepar)this.tblArtRepar.getModel()).requeryModel(repar.getCodrepar());
        this.tblArtRepar.revalidate();
        this.tblArtRepar.repaint();
    }

    public static void main(String args[]) {
        new FrmReparatii().show();
       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel Pbuton;
    private javax.swing.JPanel Pgrid;
    private javax.swing.JButton addartrepar;
    private javax.swing.JButton addrepar;
    private javax.swing.JButton anterior;
    private javax.swing.JButton cancelartrepar;
    private javax.swing.JButton cancelrepar;
    private javax.swing.JComboBox cboclient;
    private javax.swing.JComboBox cbocodrepar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton okrepar;
    private javax.swing.JButton primul;
    private javax.swing.JButton salveazaartrepar;
    private javax.swing.JButton stergartrepar;
    private javax.swing.JButton stergrepar;
    private javax.swing.JTable tblArtRepar;
    private javax.swing.JFormattedTextField txtcodrepar;
    private javax.swing.JFormattedTextField txtdatarepar;
    private javax.swing.JFormattedTextField txtvaltotalar;
    private javax.swing.JButton ultim;
    private javax.swing.JButton urmator;
    // End of variables declaration//GEN-END:variables
    
    private void refreshForm(Reparatii objfact){
        this.txtcodrepar.setValue(objfact.getCodrepar());
        if (objfact.getDatarepar()!=null)
            this.txtdatarepar.setValue(objfact.getDatarepar());
        
        else
            this.txtdatarepar.setValue(null);
       
        this.txtvaltotalar.setValue(objfact.getValtotalar());
        for (int i=0;i<this.cboclient.getItemCount();i++)
            if(((Clienti) this.cboclient.getItemAt(i)).getCodcl().equals(objfact.getCodcl()))
                this.cboclient.setSelectedIndex(i);
          
    }
private void updateBean(Reparatii objfact){
    
        objfact.setCodrepar(new java.math.BigDecimal(txtcodrepar.getValue().toString()));
        objfact.setDatarepar(new Timestamp(((java.util.Date)txtdatarepar.getValue()).getTime()));
        objfact.setCodcl(((Clienti)this.cboclient.getSelectedItem()).getCodcl());
        //objfact.setValtotalar(new java.math.BigDecimal(txtvaltotalar.getValue().toString()));
       
        
    
    }
    
private void abandon(Reparatii objfact){
         if (objfact.getStare()==Reparatii.NOU)
       {  this.cbocodrepar.removeItem(objfact);
          this.refreshForm(((Reparatii)this.cbocodrepar.getSelectedItem())); 
          
       }
     else
       try{
              objfact.refresh(this.conn);
              this.refreshForm(objfact);
               }
            catch(Exception e){
                Utilitati.tratareErori(e);
                
            }
}
     private void salveaza(Reparatii objfact){
try{           
                int stare=objfact.getStare();
                objfact.salveaza(this.conn);
                if (stare==Reparatii.STERS)
                {   this.cbocodrepar.removeItemAt(this.cbocodrepar.getSelectedIndex()); 
                     this.refreshForm(((Reparatii)this.cbocodrepar.getSelectedItem()));
                }
               }
            catch(Exception e){
                Utilitati.tratareErori(e);
            }
}
    }
 