/*
 * FrmContact.java
 *
 * Created on June 17, 2004, 8:36 PM
 */

package Formulare.interfata;

/**
 *
 * @author  Alex
 */
public class FrmContact extends javax.swing.JFrame {
    
    /** Creates new form FrmContact */
    public FrmContact() {
        initComponents();
        setSize(480,300);
        this.setLocation(280,280);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setTitle("Contact");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poze/alex.ico")));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactbuttonmouseclicked(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(210, 10, 240, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("www.guitarrepar.com");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 190, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Web:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Telefon:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 75, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("E-mail:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 90, 120, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("gibpsonel@yahoo.com");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 130, 210, 22);

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setText("Home ");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttoncontacthome(evt);
            }
        });

        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(290, 240, 100, 23);
        jToggleButton1.getAccessibleContext().setAccessibleName("Home");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("0740216665");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 200, 120, 22);

        pack();
    }//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void buttoncontacthome(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoncontacthome
        // TODO add your handling code here:
       new FrmPrincipal().show();
       this.hide();
      
    }//GEN-LAST:event_buttoncontacthome

    private void contactbuttonmouseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactbuttonmouseclicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_contactbuttonmouseclicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new FrmContact().show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    
}
