/*
 * FrmPrincipal.java
 *
 * Created on June 17, 2004, 5:59 PM
 */

package Formulare.interfata;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import utilitati.*;
import Formulare.ChitareUI.*;
import Formulare.ClientiUI.*;
import Formulare.grid.GridComplex.*;
import utilitati.*;
/**
 *
 * @author  alex
 */
public class FrmPrincipal extends javax.swing.JFrame {
    Connection conn;
    /** Creates new form FrmPrincipal */
    public FrmPrincipal() {
    
        initComponents();
        this.setSize(420, 380);
        this.setLocation(280,280);
     try{
     conn=Utilitati.getConexiune();
     }
     catch(Exception e){Utilitati.tratareErori(e);}
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JSeparator();
        mnuDateClienti = new javax.swing.JMenuItem();
        mnuDateChitare = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu4 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JSeparator();
        mnuReparatii = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenu5 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JSeparator();
        rapclienti = new javax.swing.JMenuItem();
        rapreparatii = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenu1.setText("Menu");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Menu");
        jMenuBar3.add(jMenu2);

        getContentPane().setLayout(null);

        setTitle("Aplicatia Reparatii Chitare");
        setBackground(new java.awt.Color(241, 232, 251));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(153, 153, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(237, 231, 246));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poze/chitare/stratocaster2.jpg")));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(40, 80, 300, 140);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reparatii Chitare");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 410, 40);

        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("author @ Ghibilic Alexandru");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 260, 170, 15);

        jMenu3.setToolTipText("Date Chitare, Date Clienti");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenu3.setLabel("Nomenclatoare");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenu3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu3.add(jSeparator2);

        mnuDateClienti.setText("Date Clienti");
        mnuDateClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDateClientiActionPerformed(evt);
            }
        });

        jMenu3.add(mnuDateClienti);

        mnuDateChitare.setText("Date Chitare");
        mnuDateChitare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDateChitareActionPerformed(evt);
            }
        });

        jMenu3.add(mnuDateChitare);

        jMenu3.add(jSeparator1);

        jMenuBar1.add(jMenu3);

        jMenu4.setToolTipText("Reparatii");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenu4.setLabel("Operatii");
        jMenu4.add(jSeparator4);

        mnuReparatii.setText("Reparatii");
        mnuReparatii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReparatiiActionPerformed(evt);
            }
        });

        jMenu4.add(mnuReparatii);

        jMenuItem4.setText("Incasari\n");
        jMenu4.add(jMenuItem4);

        jMenu4.add(jSeparator3);

        jMenuBar1.add(jMenu4);

        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenu5.setLabel("Rapoarte");
        jMenu5.add(jSeparator6);

        rapclienti.setText("Clienti\n");
        rapclienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapclientiActionPerformed(evt);
            }
        });
        rapclienti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rapclientiMouseClicked(evt);
            }
        });

        jMenu5.add(rapclienti);
        rapclienti.getAccessibleContext().setAccessibleName("Clienti");

        rapreparatii.setText("Clienti Reparatii\n");
        rapreparatii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapreparatiiActionPerformed(evt);
            }
        });

        jMenu5.add(rapreparatii);
        rapreparatii.getAccessibleContext().setAccessibleName("Clienti-Reparatii");

        jMenuItem7.setText("Clienti Reparatii Incasari");
        jMenu5.add(jMenuItem7);
        jMenuItem7.getAccessibleContext().setAccessibleName("Clienti Reparatii Incasari\n");

        jMenu5.add(jSeparator5);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poze/icons/meniu/INFO.GIF")));
        jMenu6.setText("Contact");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuContactmouseclicked(evt);
            }
        });

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poze/icons/meniu/exit.jpg")));
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jMenu7.setLabel("Iesire");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuIesiremouseclicked(evt);
            }
        });

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void rapreparatiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapreparatiiActionPerformed
        // TODO add your handling code here:
          try {
    /*Citesc in mediul Java fiºierul .jasper care conþine raportul compilat*/
    java.io.InputStream report = new java.io.FileInputStream(
                "D:/proiect java 2004/Proiect Alex/Rapoarte/reparatii.jasper");
    /*Completez raportul compilat cu datele din sursa JDBC ºi colecþia de parametri*/
    dori.jasper.engine.JasperPrint printReport = 
    dori.jasper.engine.JasperFillManager.fillReport(report,null,conn);
    /*Previzualizare raport*/
    dori.jasper.view.JasperViewer.viewReport(printReport, false);
    }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_rapreparatiiActionPerformed

    private void rapclientiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rapclientiMouseClicked
        
  
    }//GEN-LAST:event_rapclientiMouseClicked

    private void rapclientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapclientiActionPerformed
        // TODO add your handling code here:
    /*  try{  Runtime.getRuntime().exec("c:/Program Files/Adobe Acrobat 6.0/Reader/AcroRd32.exe  D:/proiect java 2004/Proiect Alex/Rapoarte/clienti.pdf");
              }
      catch (Exception e){};*/
         try {
    /*Citesc in mediul Java fiºierul .jasper care conþine raportul compilat*/
    java.io.InputStream report = new java.io.FileInputStream(
                "D:/proiect java 2004/Proiect Alex/Rapoarte/clienti.jasper");
    /*Completez raportul compilat cu datele din sursa JDBC ºi colecþia de parametri*/
    dori.jasper.engine.JasperPrint printReport = 
    dori.jasper.engine.JasperFillManager.fillReport(report,null,conn);
    /*Previzualizare raport*/
    dori.jasper.view.JasperViewer.viewReport(printReport, false);
    }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_rapclientiActionPerformed

    private void mnuReparatiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReparatiiActionPerformed
        // TODO add your handling code here:
        new FrmReparatii().show();
        this.hide();
        this.setLocation(280,280);
    }//GEN-LAST:event_mnuReparatiiActionPerformed

    private void mnuDateChitareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDateChitareActionPerformed
        // TODO add your handling code here:
     new Formulare.ChitareUI.FrmChitare().show();
     this.hide();
     this.setLocation(280,280);
    }//GEN-LAST:event_mnuDateChitareActionPerformed

    private void mnuDateClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDateClientiActionPerformed
        // TODO add your handling code here:
     new Formulare.ClientiUI.FormClienti().show();
     this.hide();
     this.setLocation(280,280);
    }//GEN-LAST:event_mnuDateClientiActionPerformed

    private void mnuContactmouseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuContactmouseclicked
        // TODO add your handling code here:
    new FrmContact().show();
    this.hide();
    this.setLocation(280,280);
    }//GEN-LAST:event_mnuContactmouseclicked

    private void mnuIesiremouseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuIesiremouseclicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_mnuIesiremouseclicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenu3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3AncestorAdded

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    
   public static void main(String args[]) {
       try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception ex){
            System.out.println("Se afiseaza formul Clientilor!!!!");
        }
        FrmPrincipal frm = new FrmPrincipal();
        frm.show();
        frm.setSize(400, 350);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JMenuItem mnuDateChitare;
    private javax.swing.JMenuItem mnuDateClienti;
    private javax.swing.JMenuItem mnuReparatii;
    private javax.swing.JMenuItem rapclienti;
    private javax.swing.JMenuItem rapreparatii;
    // End of variables declaration//GEN-END:variables
    
}
